/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {

        Restaurant res = new Restaurant("koko",5,1);
        res.addToRev("woow","ahmad",2);
        res.addToRev("nice","moh",3);
        res.addToRev("nice","moh",4);

        System.out.println(res.toString());
    }

}
