/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

public class App {


    public static void main(String[] args) {
        String path="C:/401-projects/java-fundamentals/linter/app/src/main/resources/gates.js";
        System.out.println(checkSemiColon(path));
    }

    public static int checkSemiColon(String path) {

        File file = new File(path);
        int numOfErrors = 0;
        if (file.length() != 0) {

            try {
                Scanner scanner = new Scanner(file);
                String line = scanner.nextLine();
                int lineNum = 1;


                while (scanner.hasNextLine()) {
                    if (!line.contains(";")
                            && !line.endsWith("}")
                            && !line.endsWith("{")
                            && !line.contains("if")
                            && !line.contains("else")
                            && !line.startsWith("//")
                            && !line.isBlank()) {
                        numOfErrors++;
                        System.out.println("Line " + lineNum + ": Missing semicolon.");
                    }
                    line = scanner.nextLine();
                    lineNum++;
                }
            } catch (FileNotFoundException e) {
                System.out.println("This provided path is wrong !!");
            }
            return numOfErrors;
        }else{
            return 0;
        }
    }


}
