/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

public class App {


    public static void main(String[] args) {
        checkSemiColon();
    }

    public static void checkSemiColon(){

            File file = new File("C:/401-projects/java-fundamentals/linter/app/src/main/resources/gates.js");

        try {
            Scanner scanner = new Scanner(file);
            String line=scanner.nextLine();
            int lineNum=1;
            while(scanner.hasNextLine()){
                if (!line.contains(";")
                        && !line.endsWith("}")
                        && !line.endsWith("{")
                        && !line.contains("if")
                        && !line.contains("else")
                        && !line.startsWith("//")
                        && !line.isBlank())
                {
                    System.out.println("Line " + lineNum + ": Missing semicolon.");
                }
                line=scanner.nextLine();
                lineNum++;
            }
        } catch (FileNotFoundException e) {
            System.out.println("This provided path is wrong !!");
        }

    }
}
