/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
  @Test public void testRestaurantConstructor(){
      Restaurant res = new Restaurant("Res1",2,4);
      assertEquals("name should be the same","Res1",res.name);
      assertEquals(2,res.numberOfStars,0.0);
      assertEquals(4,res.priceCategory,0.0);
  }

  @Test public void testReviewConstructor(){
      Review rev = new Review("delicious and nice plate","noor",5);
      assertEquals("body should be the same","delicious and nice plate",rev.body);
      assertEquals("author should be the same","noor",rev.author);
      assertEquals(5,rev.numberOfStars,0.0);

  }

  @Test public void testToStingReview(){
      Review rev = new Review("delicious and nice plate","noor",5);
      assertEquals("Review{body='delicious and nice plate', author='noor', numberOfStars=5}",rev.toString());
  }


  @Test public void testToStringRestaurant(){
      Restaurant res = new Restaurant("Res1",2,4);
      System.out.println(res);
      assertEquals("Restaurant{Restaurant Name :Res1',And its Rate is 2.0, priceCategory is 4, Reviews[]}",res.toString());

  }

  @Test public void testAddToRev(){
      Restaurant res = new Restaurant("Res1",2,4);
      res.addToRev("delicious and nice plate","noor",5);
      System.out.println(res.ArrayListReview);
      assertEquals("[Review{body='delicious and nice plate', author='noor', numberOfStars=5}]",(res.ArrayListReview.toString()));
  }

  @Test public void testChangeRating(){
      Restaurant res = new Restaurant("Res1",2,4);
      res.addToRev("delicious and nice plate","noor",5);

      assertEquals(3.5,res.numberOfStars,0.0);
  }
}




